In [3]:
import numpy as np

In [4]:
ypred = np.random.normal(0, 1, 100)
ypred[1:10] = 2.54
ypred[11:20] = -2.54
ytrue = np.zeros(100, dtype=int)
ytrue[np.random.choice(np.arange(100), 50, replace=False)] = 1

In [10]:
nitems = ypred.shape[0]
isort = np.argsort(ypred)[::-1]
pos = np.sum(ytrue)
neg = nitems - pos

In [38]:
fp = 0
tp = 0
    
fplist = list()
tplist = list()
nlist  = list()
alpha = np.max(ypred) + 1.0

for j in range(nitems):
    if not ypred[isort[j]] == alpha:
        fplist.append(fp)
        tplist.append(tp)
        nlist.append(fp + tp)
        alpha = ypred[isort[j]]
    if ytrue[isort[j]] == 1:
        tp += 1
    else:
        fp += 1
fplist.append(fp)
tplist.append(tp)
nlist.append(fp + tp)

In [39]:
np.array(tplist)

array([ 0,  1,  6,  7,  7,  7,  7,  8,  9,  9, 10, 10, 11, 11, 11, 12, 13,
       14, 14, 14, 14, 15, 15, 15, 16, 16, 17, 18, 18, 19, 19, 19, 19, 20,
       21, 22, 23, 24, 25, 26, 26, 26, 26, 26, 27, 28, 29, 30, 31, 31, 31,
       32, 32, 33, 34, 34, 35, 36, 36, 36, 36, 36, 37, 37, 38, 38, 39, 40,
       41, 42, 42, 43, 43, 44, 44, 45, 45, 45, 45, 46, 46, 46, 47, 47, 50])

In [40]:
np.array(fplist)

array([ 0,  0,  4,  4,  5,  6,  7,  7,  7,  8,  8,  9,  9, 10, 11, 11, 11,
       11, 12, 13, 14, 14, 15, 16, 16, 17, 17, 17, 18, 18, 19, 20, 21, 21,
       21, 21, 21, 21, 21, 21, 22, 23, 24, 25, 25, 25, 25, 25, 25, 26, 27,
       27, 28, 28, 28, 29, 29, 29, 30, 31, 32, 33, 33, 34, 34, 35, 35, 35,
       35, 35, 36, 36, 37, 37, 38, 38, 39, 40, 41, 41, 42, 43, 43, 44, 50])

In [41]:
np.array(nlist)

array([  0,   1,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
        21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
        34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
        47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91, 100])

In [42]:
np.array(tplist) + np.array(fplist) ==  np.array(nlist)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True], dtype=bool)

In [ ]:
isort = np.argsort(ypred)[::-1]
pos = np.sum(ytrue)
neg = nitems - pos
    
fp = list()
tp = list()
alpha = np.max(ypred) + 1.0

fpr = list()        # False positive rate
tpr = list()        # True positive rate
precision = list()
recall = list()
nsel = list()

In [ ]:
nitems = ypred.shape[0]
for j in range(nitems):
    if not ypred[isort[j]] == alpha:
        print ("At {:d}, TP: {:d}, FP: {:d}".format(j, tp, fp))
        fpr.append(fp / neg)
        tpr.append(tp / pos)
        if (tp + fp) == 0: 
            precision.append(1.0)
            recall.append(0.0)
        else:
            precision.append(tp / (tp + fp))
            recall.append(tp / pos)
        nsel.append(j)
        alpha = ypred[isort[j]]

    if ytrue[isort[j]] == 1:
        print("TP")
        tp += 1
    else:
        print("FP")
        fp += 1 

In [ ]:
tp

In [ ]:
len(precision)

In [ ]:
fp / neg

In [ ]:
neg